### ISSUE TITLE
full disk access

### ISSUE THREAD

**Issue by gedw99** [dgl/go-safari-bookmarks#1]
by packaging this as a .app and the right plist, it shoudl prompt to open the system preferences to give access.

a bit easier for usage at least.

**Comment by dgl** [comment]
There's no official apple API for that, so it would basically amount to presenting the instructions to the user.

https://github.com/MacPaw/PermissionsKit is potentially interesting, but for Full Disk Access it amounts to opening a settings URL. Maybe it would make sense for the example tools to do that, but I don't think it makes sense in the library.

**Comment by dgl** [comment]
I added a way to request it and did it in the example apps: https://github.com/dgl/go-safari-bookmarks/commit/9028db70936e5c23f9591c628850f315acb02951 -- that's the best it can do, and it doesn't need an .app or anything.

**Comment by gedw99** [comment]
Ah thanks @dgl 

will try out you tips :)

**Comment by gedw99** [comment]
https://github.com/MacPaw/PermissionsKit/tree/master Looks like a great archityoe for that problem.

I might convert their calls into golang sys calls . So can just use from golang without the baggage

**Comment by gedw99** [comment]
So then as a cli it just works hopefully :)
